### ISSUE TITLE
Only Converts the first form into pdf

### ISSUE THREAD

**Issue by sephma** [susom/multi-signature-consent#1]
I haven't gotten the emLogger configured to capture any errors (don't kill me), but so far everything thing appears to function as expected (saves to field, added to file repo) other than the additional forms not being included in the merged pdf. I installed from the External Module repo on REDCap v10.0.4

**Comment by 123andy** [comment]
Can you share more of your configuration (like a screen shot of the module config page) and share the XML file for the project?

**Comment by sephma** [comment]
Sure thing. Thanks. 
[EConsentTemplate_2020-07-01_2221.REDCap.xml.zip](https://github.com/susom/multi-signature-consent/files/4861629/EConsentTemplate_2020-07-01_2221.REDCap.xml.zip)


<img width="796" alt="image" src="https://user-images.githubusercontent.com/18578388/86308987-93851280-bbe8-11ea-92cc-2bbdd5166a17.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/18578388/86309023-a8fa3c80-bbe8-11ea-8677-6653aaf44330.png">

**Comment by 123andy** [comment]
Hello @sephma - I was able to use your XML and it worked (mostly) on my system. 

One thing that did not work as the saving to the file repository.  This is because the two surveys in the project are both configured to use the econsent module - so they are already being archived.  In order for this EM to 'archive' the combined survey it needs to have an available survey that is not configured with econsent framework.  So, if you made the 'multi-signature' you could then save the multi-form pdf to the file archive.  I've done this with a new setting for record #2.

![image](https://user-images.githubusercontent.com/7461553/87098821-0bf95e00-c1fd-11ea-88b0-ff9c5b93cc8c.png)

![image](https://user-images.githubusercontent.com/7461553/87099001-80cc9800-c1fd-11ea-99ab-131006a500c9.png)

If it isn't working for you - I wonder if it is a server or configuration difference.  How do you store your edocs?  Do you use webdav or S3 storage or anything like that?

**Comment by sephma** [comment]
thanks @123andy . I tried a bunch of different setups for each form and so far, on my deployment, only the first form is converted to pdf and saved. We use local storage for edocs. 
I'll play around some more and see if I can find details that might help troubleshoot. 
Thanks for your help

**Comment by 123andy** [comment]
I'm going to close unless you have further issues.  Good luck!

**Comment by jouterleys** [comment]
Hello,

I was wondering if I could reopen this issue. I am having the same behavior. No merging multiple instruments but everything else works perfectly.

The Server info is: REDCap 10.6.12 · PHP 5.6.40 (Linux/Unix OS) · MariaDB 5.5.56

We use local storage and the location is essentially the default.

Could it be an out of date PHP issue? What versions have you tested on?
